name: HumineKingdom
author: Aymegike
version: 3.5
main: com.aymegike.huminekingdom.HumineKingdom
commands:
    kingdom:
        description: Gestion des royaumes
    ranking:
        description: Classement des royaumes