## Welcome to HumineCraft ##

URL-PACK: www.directeDownloadLink.com/YourPack
URL-FinalPACK: www.directeDownloadLink.com/YourPack
location:
   spaceShip:
     world: world
     x: 0
     y: 0
     z: 0
   spawn:
     world: world
     x: 0
     y: 0
     z: 0